#!/usr/bin/env bash
# Usage: lego example [command]
# Summary: Collection of BASH Sub Example Scripts
# Help: These commands are mostly used as examples and for testing lego modifications

set -e

lego help example
